"""Mac Worker execution for closed local business-intelligence tasks."""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from typing import Any, Protocol
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field

from picotoopet_core.db.database import Database
from picotoopet_core.domain.models import TaskRecord
from picotoopet_core.queue.diagnostic_repository import DiagnosticQueueRepository
from picotoopet_core.worker.handlers import HandlerResult

from .local_intelligence import ADAPTER_VERSION, LocalIntelligenceError
from .models import (
    BusinessAnalysisProfile,
    BusinessQualityOutcome,
    BusinessResultPackageRecord,
    BusinessRunStatus,
    BusinessWorkPackageStatus,
    DeepAiHandoffRecord,
)
from .preprocess import AnalysisChunk, PreprocessedAnalysis, preprocess_work_package
from .profiles import AnalysisProfileDefinition, LocalIntelligenceResult, profile_definition
from .quality import BusinessQualityGate
from .repository import BusinessRepository
from .store import BusinessArtifactStore


class _LocalAdapter(Protocol):
    def run(
        self,
        profile: AnalysisProfileDefinition,
        context: dict[str, Any],
        *,
        correction: str | None = None,
    ) -> dict[str, Any]: ...


class BusinessTaskPayload(BaseModel):
    """Strict identifier-only task contract generated by Mac Core."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    work_package_id: str
    source_digest: str = Field(pattern=r"^[0-9a-f]{64}$")
    analysis_profile: BusinessAnalysisProfile

    @classmethod
    def from_task(cls, task: TaskRecord) -> BusinessTaskPayload:
        value = cls.model_validate(task.payload)
        UUID(value.work_package_id)
        return value


class BusinessLocalIntelligenceCoordinator:
    """Preprocess, infer and quality-check without giving the model any tools."""

    TASK_TYPE = "business.local_intelligence.v1"
    CAPABILITY = "local.intelligence.v1"
    MAX_MODEL_ATTEMPTS_PER_STAGE = 2
    MAX_HANDOFF_EVIDENCE = 24

    def __init__(
        self,
        *,
        database: Database,
        queue: DiagnosticQueueRepository,
        repository: BusinessRepository,
        store: BusinessArtifactStore,
        adapter: _LocalAdapter,
        configured_model_id: str,
    ) -> None:
        self.database = database
        self.queue = queue
        self.repository = repository
        self.store = store
        self.adapter = adapter
        self.configured_model_id = configured_model_id
        self.quality = BusinessQualityGate()

    def handler(self, task: TaskRecord) -> HandlerResult:
        payload = BusinessTaskPayload.from_task(task)
        package = self.repository.get_work_package(payload.work_package_id)
        if package.source_digest != payload.source_digest:
            raise ValueError("BUSINESS_SOURCE_DIGEST_MISMATCH")
        if package.analysis_profile is not payload.analysis_profile:
            raise ValueError("BUSINESS_PROFILE_MISMATCH")
        if package.status is BusinessWorkPackageStatus.COMPLETED:
            return HandlerResult(
                summary={
                    "work_package_id": package.work_package_id,
                    "status": BusinessWorkPackageStatus.COMPLETED.value,
                }
            )
        if package.status in {
            BusinessWorkPackageStatus.REJECTED,
            BusinessWorkPackageStatus.FAILED,
            BusinessWorkPackageStatus.CANCELLED,
        }:
            raise ValueError("BUSINESS_PACKAGE_NOT_EXECUTABLE")
        if package.package_object_relpath is None:
            raise ValueError("BUSINESS_PACKAGE_NOT_IMMUTABLE")

        profile = profile_definition(package.analysis_profile)
        run = self.repository.create_or_get_run(
            work_package_id=package.work_package_id,
            analysis_profile=package.analysis_profile,
            source_digest=package.source_digest,
            model_adapter_version=ADAPTER_VERSION,
            configured_model_id=self.configured_model_id,
            template_version=profile.template_version,
            idempotency_key=f"business-run:{package.work_package_id}:v1",
        )
        existing_result = self.repository.result_for(package.work_package_id)
        if existing_result is not None:
            self.repository.transition_work_package(
                package.work_package_id,
                BusinessWorkPackageStatus.COMPLETED,
                preprocess_digest=existing_result.preprocess_digest,
                result_package_id=existing_result.result_package_id,
                finished=True,
            )
            return self._summary(package.work_package_id, BusinessWorkPackageStatus.COMPLETED)
        existing_handoff = self.repository.handoff_for(package.work_package_id)
        if existing_handoff is not None:
            self.repository.transition_work_package(
                package.work_package_id,
                BusinessWorkPackageStatus.NEEDS_DEEP_AI,
                deep_ai_handoff_id=existing_handoff.handoff_id,
                finished=True,
            )
            return self._summary(package.work_package_id, BusinessWorkPackageStatus.NEEDS_DEEP_AI)

        self.repository.transition_work_package(
            package.work_package_id,
            BusinessWorkPackageStatus.PREPROCESSING,
        )
        self.repository.update_run(run.run_id, status=BusinessRunStatus.PREPROCESSING)
        immutable_package = self.store.open_package(package.package_object_relpath)
        preprocessed = preprocess_work_package(immutable_package, profile)
        if preprocessed.source_digest != package.source_digest:
            raise ValueError("BUSINESS_PREPROCESS_DIGEST_MISMATCH")
        self.repository.transition_work_package(
            package.work_package_id,
            BusinessWorkPackageStatus.LOCAL_INFERENCE,
            preprocess_digest=preprocessed.preprocess_digest,
        )
        run = self.repository.update_run(
            run.run_id,
            status=BusinessRunStatus.LOCAL_INFERENCE,
            preprocess_digest=preprocessed.preprocess_digest,
        )

        try:
            final_result, decision, last_raw = self._infer_package(
                run_id=run.run_id,
                profile=profile,
                preprocessed=preprocessed,
            )
        except LocalIntelligenceError as error:
            self.repository.update_run(
                run.run_id,
                status=BusinessRunStatus.NEEDS_HUMAN,
                quality_outcome=BusinessQualityOutcome.NEEDS_HUMAN,
                failure_code=error.code,
                error_message="Local intelligence endpoint is unavailable or returned an invalid transport response.",
                finished=True,
            )
            self.repository.transition_work_package(
                package.work_package_id,
                BusinessWorkPackageStatus.NEEDS_HUMAN,
                failure_code=error.code,
                error_message="Local intelligence requires attention.",
                finished=True,
            )
            return self._summary(package.work_package_id, BusinessWorkPackageStatus.NEEDS_HUMAN)

        self.repository.transition_work_package(
            package.work_package_id,
            BusinessWorkPackageStatus.QUALITY_CHECK,
        )
        self.repository.update_run(run.run_id, status=BusinessRunStatus.QUALITY_CHECK)

        if decision is BusinessQualityOutcome.PASS and final_result is not None:
            return self._finish_pass(
                run_id=run.run_id,
                package=package,
                profile=profile,
                preprocessed=preprocessed,
                result=final_result,
            )
        if decision is BusinessQualityOutcome.NEEDS_HUMAN:
            self.repository.update_run(
                run.run_id,
                status=BusinessRunStatus.NEEDS_HUMAN,
                quality_outcome=decision,
                finished=True,
            )
            self.repository.transition_work_package(
                package.work_package_id,
                BusinessWorkPackageStatus.NEEDS_HUMAN,
                finished=True,
            )
            return self._summary(package.work_package_id, BusinessWorkPackageStatus.NEEDS_HUMAN)
        if decision is BusinessQualityOutcome.REJECT:
            self.repository.update_run(
                run.run_id,
                status=BusinessRunStatus.FAILED,
                quality_outcome=decision,
                failure_code="BUSINESS_RESULT_REJECTED",
                finished=True,
            )
            self.repository.transition_work_package(
                package.work_package_id,
                BusinessWorkPackageStatus.FAILED,
                failure_code="BUSINESS_RESULT_REJECTED",
                error_message="Local intelligence result violated the closed quality contract.",
                finished=True,
            )
            return self._summary(package.work_package_id, BusinessWorkPackageStatus.FAILED)
        return self._finish_deep_ai(
            run_id=run.run_id,
            package=package,
            profile=profile,
            preprocessed=preprocessed,
            local_result=last_raw,
            reasons=["LOCAL_RESULT_REQUIRES_DEEP_AI"],
        )

    def _infer_package(
        self,
        *,
        run_id: str,
        profile: AnalysisProfileDefinition,
        preprocessed: PreprocessedAnalysis,
    ) -> tuple[LocalIntelligenceResult | None, BusinessQualityOutcome, dict[str, Any]]:
        chunk_results: list[dict[str, Any]] = []
        last_raw: dict[str, Any] = {}
        for chunk in preprocessed.chunks:
            parsed, outcome, raw = self._infer_stage(
                run_id=run_id,
                profile=profile,
                preprocessed=preprocessed,
                context=chunk.context,
                stage_key=f"chunk:{chunk.chunk_index}",
            )
            last_raw = raw
            if outcome is not BusinessQualityOutcome.PASS or parsed is None:
                return parsed, self._attention_outcome(outcome), raw
            chunk_results.append(parsed.model_dump(mode="json"))

        if len(chunk_results) == 1:
            return LocalIntelligenceResult.model_validate(chunk_results[0]), BusinessQualityOutcome.PASS, chunk_results[0]

        synthesis_context = {
            "schema_version": "1.0",
            "analysis_profile": profile.profile_id.value,
            "objective": "Synthesize the validated chunk findings into one evidence-grounded ranked result.",
            "aggregate_facts": preprocessed.aggregate_facts,
            "chunk_results": chunk_results,
            "allowed_evidence_ids": [item.evidence_id for item in preprocessed.evidence_records],
        }
        return self._infer_stage(
            run_id=run_id,
            profile=profile,
            preprocessed=preprocessed,
            context=synthesis_context,
            stage_key="synthesis",
        )

    def _infer_stage(
        self,
        *,
        run_id: str,
        profile: AnalysisProfileDefinition,
        preprocessed: PreprocessedAnalysis,
        context: dict[str, Any],
        stage_key: str,
    ) -> tuple[LocalIntelligenceResult | None, BusinessQualityOutcome, dict[str, Any]]:
        correction: str | None = None
        last_raw: dict[str, Any] = {}
        for attempt in range(1, self.MAX_MODEL_ATTEMPTS_PER_STAGE + 1):
            self._record_stage_attempt(run_id, stage_key, attempt, context)
            raw = self.adapter.run(profile, context, correction=correction)
            last_raw = raw
            quality, parsed = self.quality.evaluate(profile, preprocessed, raw)
            self._record_stage_result(run_id, stage_key, attempt, quality.outcome, raw)
            if quality.outcome is BusinessQualityOutcome.PASS:
                assert parsed is not None
                return parsed, quality.outcome, raw
            if quality.outcome is not BusinessQualityOutcome.RETRY:
                return parsed, quality.outcome, raw
            correction = quality.correction_instruction
        return None, BusinessQualityOutcome.NEEDS_DEEP_AI, last_raw

    def _record_stage_attempt(
        self,
        run_id: str,
        stage_key: str,
        attempt: int,
        context: dict[str, Any],
    ) -> None:
        context_digest = self._digest(context)
        now = datetime.now(UTC).isoformat()
        chunk_index = self._stage_index(stage_key)
        row = self.database.fetchone(
            "SELECT chunk_run_id,model_attempts FROM local_intelligence_chunks WHERE run_id=? AND chunk_index=?",
            (run_id, chunk_index),
        )
        if row is None:
            self.database.execute(
                "INSERT INTO local_intelligence_chunks("
                "chunk_run_id,run_id,chunk_index,context_digest,status,model_attempts,created_at,updated_at"
                ") VALUES (?,?,?,?,?,?,?,?)",
                (str(uuid4()), run_id, chunk_index, context_digest, "Running", attempt, now, now),
            )
        else:
            if int(row["model_attempts"]) >= attempt:
                # Crash recovery never broadens the number of permitted inference attempts.
                if int(row["model_attempts"]) >= self.MAX_MODEL_ATTEMPTS_PER_STAGE:
                    raise LocalIntelligenceError("LOCAL_MODEL_ATTEMPT_BUDGET_EXHAUSTED")
            self.database.execute(
                "UPDATE local_intelligence_chunks SET status='Running',model_attempts=?,updated_at=? "
                "WHERE run_id=? AND chunk_index=?",
                (attempt, now, run_id, chunk_index),
            )
        current = self.repository.get_run(run_id)
        total_attempts = max(current.model_attempts, 0) + 1
        self.repository.update_run(
            run_id,
            status=BusinessRunStatus.LOCAL_INFERENCE,
            model_attempts=total_attempts,
        )

    def _record_stage_result(
        self,
        run_id: str,
        stage_key: str,
        attempt: int,
        outcome: BusinessQualityOutcome,
        raw: dict[str, Any],
    ) -> None:
        self.database.execute(
            "UPDATE local_intelligence_chunks SET status=?,result_digest=?,result_json=?,updated_at=? "
            "WHERE run_id=? AND chunk_index=?",
            (
                outcome.value,
                self._digest(raw),
                json.dumps(raw, ensure_ascii=False, sort_keys=True, separators=(",", ":")),
                datetime.now(UTC).isoformat(),
                run_id,
                self._stage_index(stage_key),
            ),
        )

    def _finish_pass(
        self,
        *,
        run_id: str,
        package,
        profile: AnalysisProfileDefinition,
        preprocessed: PreprocessedAnalysis,
        result: LocalIntelligenceResult,
    ) -> HandlerResult:
        result_id = str(uuid4())
        result_data = result.model_dump(mode="json")
        result_digest = self._digest(result_data)
        payload = {
            "schema_version": "1.0",
            "result_package_id": result_id,
            "work_package_id": package.work_package_id,
            "producer_id": package.producer_id,
            "project_key": package.project_key,
            "analysis_profile": package.analysis_profile.value,
            "status": "Completed",
            "source_digest": package.source_digest,
            "preprocess_digest": preprocessed.preprocess_digest,
            "model_adapter_version": ADAPTER_VERSION,
            "configured_model_id": self.configured_model_id,
            "template_version": profile.template_version,
            "quality_outcome": BusinessQualityOutcome.PASS.value,
            "completed_at": datetime.now(UTC).isoformat(),
            "result_digest": result_digest,
            "result": result_data,
            "warnings": result.warnings,
        }
        relative, _package_digest = self.store.write_result_package(
            result_package_id=result_id,
            payload=payload,
        )
        record = BusinessResultPackageRecord(
            result_package_id=result_id,
            work_package_id=package.work_package_id,
            analysis_profile=package.analysis_profile,
            source_digest=package.source_digest,
            preprocess_digest=preprocessed.preprocess_digest,
            model_adapter_version=ADAPTER_VERSION,
            configured_model_id=self.configured_model_id,
            template_version=profile.template_version,
            quality_outcome=BusinessQualityOutcome.PASS,
            result_digest=result_digest,
            package_relpath=relative,
            result=result_data,
            warnings=result.warnings,
            created_at=datetime.now(UTC),
        )
        saved = self.repository.save_result(record)
        self.repository.update_run(
            run_id,
            status=BusinessRunStatus.COMPLETED,
            quality_outcome=BusinessQualityOutcome.PASS,
            finished=True,
        )
        self.repository.transition_work_package(
            package.work_package_id,
            BusinessWorkPackageStatus.COMPLETED,
            preprocess_digest=preprocessed.preprocess_digest,
            result_package_id=saved.result_package_id,
            finished=True,
        )
        return self._summary(package.work_package_id, BusinessWorkPackageStatus.COMPLETED)

    def _finish_deep_ai(
        self,
        *,
        run_id: str,
        package,
        profile: AnalysisProfileDefinition,
        preprocessed: PreprocessedAnalysis,
        local_result: dict[str, Any],
        reasons: list[str],
    ) -> HandlerResult:
        handoff_id = str(uuid4())
        local_result_digest = self._digest(local_result)
        payload = {
            "schema_version": "1.0",
            "handoff_id": handoff_id,
            "work_package_id": package.work_package_id,
            "problem": package.objective,
            "analysis_profile": package.analysis_profile.value,
            "source_digest": package.source_digest,
            "preprocess_digest": preprocessed.preprocess_digest,
            "aggregate_facts": preprocessed.aggregate_facts,
            "evidence": [
                {
                    "evidence_id": item.evidence_id,
                    "artifact_id": item.artifact_id,
                    "excerpt": self._sanitize_value(item.value),
                }
                for item in preprocessed.evidence_records[: self.MAX_HANDOFF_EVIDENCE]
            ],
            "local_result": self._sanitize_value(local_result),
            "quality_reasons": reasons,
            "questions": [
                "Resolve the quality-gate failure using only supplied evidence.",
                "Return the corrected structured analysis using the exact return schema.",
            ],
            "return_schema": profile.return_schema,
            "local_result_digest": local_result_digest,
        }
        relative, package_digest = self.store.write_handoff_package(
            handoff_id=handoff_id,
            payload=payload,
        )
        record = DeepAiHandoffRecord(
            handoff_id=handoff_id,
            work_package_id=package.work_package_id,
            source_digest=package.source_digest,
            preprocess_digest=preprocessed.preprocess_digest,
            local_result_digest=local_result_digest,
            quality_reasons=reasons,
            return_schema=profile.return_schema,
            package_digest=package_digest,
            package_relpath=relative,
            status="ManualReady",
            created_at=datetime.now(UTC),
        )
        saved = self.repository.save_handoff(record)
        self.repository.update_run(
            run_id,
            status=BusinessRunStatus.NEEDS_DEEP_AI,
            quality_outcome=BusinessQualityOutcome.NEEDS_DEEP_AI,
            finished=True,
        )
        self.repository.transition_work_package(
            package.work_package_id,
            BusinessWorkPackageStatus.NEEDS_DEEP_AI,
            preprocess_digest=preprocessed.preprocess_digest,
            deep_ai_handoff_id=saved.handoff_id,
            finished=True,
        )
        return self._summary(package.work_package_id, BusinessWorkPackageStatus.NEEDS_DEEP_AI)

    @staticmethod
    def _summary(work_package_id: str, status: BusinessWorkPackageStatus) -> HandlerResult:
        return HandlerResult(summary={"work_package_id": work_package_id, "status": status.value})

    @staticmethod
    def _attention_outcome(outcome: BusinessQualityOutcome) -> BusinessQualityOutcome:
        if outcome is BusinessQualityOutcome.RETRY:
            return BusinessQualityOutcome.NEEDS_DEEP_AI
        return outcome

    @staticmethod
    def _stage_index(stage_key: str) -> int:
        if stage_key == "synthesis":
            return 1_000_000
        if not stage_key.startswith("chunk:"):
            raise ValueError("invalid local intelligence stage")
        return int(stage_key.split(":", 1)[1])

    @staticmethod
    def _digest(value: Any) -> str:
        encoded = json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            default=str,
        ).encode("utf-8")
        return hashlib.sha256(encoded).hexdigest()

    @classmethod
    def _sanitize_value(cls, value: Any) -> Any:
        """Bound manual Handoff content and remove obvious secret-bearing fields."""

        if isinstance(value, dict):
            sanitized: dict[str, Any] = {}
            for key, item in list(value.items())[:40]:
                lowered = str(key).lower()
                if any(marker in lowered for marker in ("token", "password", "secret", "authorization", "cookie")):
                    sanitized[str(key)] = "***REDACTED***"
                else:
                    sanitized[str(key)] = cls._sanitize_value(item)
            return sanitized
        if isinstance(value, list):
            return [cls._sanitize_value(item) for item in value[:40]]
        if isinstance(value, str):
            return value[:2000]
        return value
