"""Durable fixed-size upload protocol for business Work Package archives."""

from __future__ import annotations

import hashlib
from pathlib import Path

from .archive import MAX_COMPRESSED_BYTES, WorkPackageArchiveError, validate_work_package_archive
from .models import BusinessUploadSessionRecord, BusinessWorkPackageStatus, WorkPackageManifest, WorkPackageRecord
from .repository import BusinessRepository
from .store import BusinessArtifactStore

CHUNK_SIZE_BYTES = 4 * 1024 * 1024


class BusinessUploadError(ValueError):
    def __init__(self, code: str, message: str | None = None) -> None:
        super().__init__(message or code)
        self.code = code


class BusinessUploadCoordinator:
    """Resume-safe upload writer; producer never chooses a Core filesystem path."""

    def __init__(self, repository: BusinessRepository, store: BusinessArtifactStore) -> None:
        self.repository = repository
        self.store = store

    def prepare(
        self,
        manifest: WorkPackageManifest,
        *,
        source_digest: str,
        total_size_bytes: int,
    ) -> tuple[WorkPackageRecord, BusinessUploadSessionRecord]:
        if total_size_bytes < 1 or total_size_bytes > MAX_COMPRESSED_BYTES:
            raise BusinessUploadError("PACKAGE_SIZE_INVALID")
        if len(source_digest) != 64 or any(c not in "0123456789abcdef" for c in source_digest):
            raise BusinessUploadError("SOURCE_DIGEST_INVALID")
        package = self.repository.create_or_get_work_package(
            manifest,
            source_digest=source_digest,
            compressed_size_bytes=total_size_bytes,
        )
        # Create a UUID session first so the path is generated by Core, never the producer.
        existing = self.repository.database.fetchone(
            "SELECT * FROM business_upload_sessions WHERE work_package_id=?",
            (package.work_package_id,),
        )
        if existing is not None:
            session = self.repository.get_upload_session(existing["upload_session_id"])
            if session.source_digest != source_digest or session.total_size_bytes != total_size_bytes:
                raise BusinessUploadError("UPLOAD_IDENTITY_CONFLICT")
            return package, session

        # Repository generates session UUID; use a temporary Core-generated UUID-like placeholder
        # only to obtain the persisted identity, then bind the managed relative path once.
        session = self.repository.create_upload_session(
            work_package_id=package.work_package_id,
            source_digest=source_digest,
            total_size_bytes=total_size_bytes,
            chunk_size_bytes=CHUNK_SIZE_BYTES,
            staging_relpath="pending",
        )
        staging = self.store.staging_archive(session.upload_session_id)
        relative = self.store.relative_to_root(staging)
        self.repository.database.execute(
            "UPDATE business_upload_sessions SET staging_relpath=? WHERE upload_session_id=?",
            (relative, session.upload_session_id),
        )
        return package, self.repository.get_upload_session(session.upload_session_id)

    def write_chunk(
        self,
        upload_session_id: str,
        *,
        offset: int,
        expected_sha256: str,
        payload: bytes,
    ) -> BusinessUploadSessionRecord:
        session = self.repository.get_upload_session(upload_session_id)
        if session.status == "Finalized":
            return session
        if not payload or len(payload) > CHUNK_SIZE_BYTES:
            raise BusinessUploadError("CHUNK_SIZE_INVALID")
        if offset < 0 or offset + len(payload) > session.total_size_bytes:
            raise BusinessUploadError("CHUNK_RANGE_INVALID")
        actual_digest = hashlib.sha256(payload).hexdigest()
        if actual_digest != expected_sha256:
            raise BusinessUploadError("CHUNK_DIGEST_MISMATCH")

        existing = self.repository.database.fetchone(
            "SELECT size_bytes,sha256 FROM business_upload_chunks WHERE upload_session_id=? AND chunk_offset=?",
            (upload_session_id, offset),
        )
        if existing is not None:
            if int(existing["size_bytes"]) != len(payload) or existing["sha256"] != actual_digest:
                raise BusinessUploadError("CHUNK_CONFLICT")
            return self.repository.get_upload_session(upload_session_id)

        if offset != session.verified_size_bytes:
            raise BusinessUploadError("CHUNK_OFFSET_INVALID")
        if offset + len(payload) < session.total_size_bytes and len(payload) != CHUNK_SIZE_BYTES:
            raise BusinessUploadError("CHUNK_SIZE_INVALID")

        staging = self.store.resolve_managed_relative(session.staging_relpath)
        staging.parent.mkdir(parents=True, exist_ok=True)
        mode = "r+b" if staging.exists() else "wb"
        with staging.open(mode) as handle:
            handle.seek(offset)
            handle.write(payload)
            handle.flush()
        self.repository.record_upload_chunk(
            upload_session_id=upload_session_id,
            offset=offset,
            size_bytes=len(payload),
            sha256=actual_digest,
        )
        return self.repository.get_upload_session(upload_session_id)

    def finalize(self, upload_session_id: str) -> WorkPackageRecord:
        session = self.repository.get_upload_session(upload_session_id)
        package = self.repository.get_work_package(session.work_package_id)
        if session.status == "Finalized":
            return package
        if session.verified_size_bytes != session.total_size_bytes:
            raise BusinessUploadError("UPLOAD_INCOMPLETE")
        staging = self.store.resolve_managed_relative(session.staging_relpath)
        if not staging.is_file() or staging.stat().st_size != session.total_size_bytes:
            raise BusinessUploadError("UPLOAD_STAGING_INVALID")
        actual_digest = self.store.sha256_file(staging)
        if actual_digest != session.source_digest:
            raise BusinessUploadError("SOURCE_DIGEST_MISMATCH")

        self.repository.transition_work_package(
            package.work_package_id,
            BusinessWorkPackageStatus.VALIDATING,
        )
        try:
            validated = validate_work_package_archive(staging)
            if validated.manifest.package_id != package.work_package_id:
                raise WorkPackageArchiveError("package_id_mismatch")
            if validated.source_digest != package.source_digest:
                raise WorkPackageArchiveError("source_digest_mismatch")
            manifest = self.repository.manifest_for(package.work_package_id)
            if validated.manifest != manifest:
                raise WorkPackageArchiveError("manifest_identity_mismatch")
            relative, _ = self.store.promote_package(validated)
        except WorkPackageArchiveError as error:
            self.repository.transition_work_package(
                package.work_package_id,
                BusinessWorkPackageStatus.REJECTED,
                failure_code=error.code,
                error_message="Work Package validation failed.",
                finished=True,
            )
            raise BusinessUploadError(error.code) from error

        self.repository.finalize_upload_session(upload_session_id)
        return self.repository.transition_work_package(
            package.work_package_id,
            BusinessWorkPackageStatus.READY,
            uncompressed_size_bytes=validated.uncompressed_size_bytes,
            package_object_relpath=relative,
        )
